name: Main

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".github/dependabot.yml"
env:
  CARGO_TERM_COLOR: always

jobs:

  format_check:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  clippy_check:
    name: Check Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  test-server-socket:
    strategy:
      fail-fast: false
      matrix:
        features: [ use-udp, use-webrtc ]
        package:
          [
            naia-server-socket,
          ]
    name: Test Server Socket
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package ${{ matrix.package }} --features "${{ matrix.features }}"

  test-servers:
    name: Test Servers
    strategy:
      fail-fast: false
      matrix:
        package:
          [
            naia-server,
            naia-hecs-server,
            naia-bevy-server,
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package ${{ matrix.package }} --features "use-udp"

  test-clients-and-shared:
    name: Test Clients
    strategy:
      fail-fast: false
      matrix:
        features: [ mquad, wbindgen ]
        package:
          [
            naia-client-socket,
            naia-socket-shared,
            naia-client,
            naia-shared,
            naia-hecs-client,
            naia-hecs-shared,
          ]

    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package ${{ matrix.package }} --features "${{ matrix.features }}"

  test:
    name: Test all other crates
    strategy:
      fail-fast: false
      matrix:
        package:
          [
            naia-bevy-client,
            naia-bevy-shared,
            naia-serde-derive,
            naia-demo-world,
            naia-empty-world,
            naia-serde,
            naia-test,
            naia-parse,
            naia-derive,
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libxi-dev libgl1-mesa-dev
      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package ${{ matrix.package }}

  build-server-demos:
    name: Build Server Demos
    strategy:
      fail-fast: false
      matrix:
        package:
          [
            naia-macroquad-server-demo,
            naia-bevy-server-demo,
            naia-basic-server-demo,
            naia-server-socket-demo,
            naia-hecs-server-demo,
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package ${{ matrix.package }} --features "use-udp"

  build-client-demos:
    name: Build Client Demos
    strategy:
      fail-fast: false
      matrix:
        package:
          [
            naia-macroquad-client-demo,
            naia-bevy-client-demo,
            naia-hecs-client-demo,
          ]

    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package ${{ matrix.package }}

  build-multi-feature-client-demos:
    name: Build Client Demos (w/ Multiple Features)
    strategy:
      fail-fast: false
      matrix:
        features: [ mquad, wbindgen ]
        package:
          [
            naia-basic-demo-client,
            naia-socket-demo-client,
          ]

    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package ${{ matrix.package }} --features "${{ matrix.features }}"